---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: madoka-os
description: A customized fedora-silverblue image for chinese developer & anime lover

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42

modules:
  - type: dnf
    repos:
      files:
        - https://pkg.surfacelinux.com/fedora/linux-surface.repo
      keys:
        - https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc
    install:
      allow-erasing: true
      skip-broken: true

      packages:
        - kernel-surface
        - kernel-surface-core
        - kernel-surface-modules
        - kernel-surface-modules-extra

        - iptsd
        - libwacom-surface
        - surface-control
        - surface-secureboot

  - type: files
    files:
      - source: system
        destination: /

  - type: script
    snippets:
      - chmod +x /usr/bin/mihomo

  - type: script
    snippets:
      - curl -fsSL https://cli.github.com/packages/rpm/gh-cli.repo -o /etc/yum.repos.d/gh-cli.repo

  - type: dnf
    repos:
      nonfree: rpmfusion
      copr:
        - atim/starship
        - scottames/ghostty
        - alternate/keyd
    install:
      allow-erasing: true
      skip-broken: true
      packages:
        # --- Shell ---
        - zsh
        - lsd
        - bat
        - starship

        # --- Tools ---
        - util-linux-user
        - fastfetch
        - powertop
        - less
        - wl-clipboard
        - keyd

        # --- Development ---
        - vim
        - distrobox
        - podman-compose
        - gh

        # --- Zip ---
        - p7zip
        - p7zip-plugins
        - unrar

        # --- Input ---
        - ibus-libpinyin

        # --- Desktop --- (For no flathub package)
        - ghostty
        - epiphany
        - snapshot
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: brew
    brew-analytics: false

  - type: systemd
    system:
      enabled:
        - mihomo.service

  - type: script
    snippets:
      - sed -i 's|SHELL=/bin/bash|SHELL=/bin/zsh|' /etc/default/useradd

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: dnf
    install:
      packages:
        - google-noto-sans-fonts
        - google-noto-serif-fonts
        - google-noto-cjk-fonts
        - google-noto-emoji-color-fonts
        - google-noto-emoji-fonts

        - wqy-microhei-fonts
        - wqy-zenhei-fonts

        - langpacks-zh_CN

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - runtime/org.freedesktop.Platform/x86_64/25.08

          - org.gnome.Loupe
          - org.gnome.Showtime
          - org.gnome.Builder
          - org.gnome.Boxes
          - net.nokyan.Resources
          - org.gnome.gitlab.somas.Apostrophe
          - com.mattjakeman.ExtensionManager
          - ar.xjuan.Cambalache
          - com.google.Chrome
          - com.usebottles.bottles
          - dev.zed.Zed-Preview
          - org.localsend.localsend_app

          - org.gtk.Gtk3theme.adw-gtk3
          - org.gtk.Gtk3theme.adw-gtk3-dark
      - notify: false
        scope: user
        install:
          - com.qq.QQ
          - com.tencent.WeChat
          - org.telegram.desktop

  - type: gschema-overrides
    include:
      - zz-madoka.gschema.override

  - type: gnome-extensions
    install:
      - AppIndicator and KStatusNotifierItem Support

  - type: script
    scripts:
      - set-china-mirrors.sh
      - set-grub-config.sh

  - type: os-release
    properties:
      NAME: MadokaOS
      ID: madoka
      ID_LIKE: fedora
      PRETTY_NAME: "Madoka OS"
      VARIANT: "Surface Edition"
      VARIANT_ID: surface

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
