if [ -f /etc/profile ]; then
    source /etc/profile
fi

if command -v lsd &> /dev/null; then
    alias ls='lsd'
    alias ll='lsd -l'
    alias la='lsd -la'
    alias tree='lsd --tree'
fi

if command -v starship &> /dev/null; then
    eval "$(starship init zsh)"
fi
